### ISSUE TITLE
Wrong line numbers

### ISSUE THREAD

**Issue by lolmaus** [nex3/firesass#15]
Hi!

I'm using `FireSass 0.0.9`, `SASS 3.2.1` and `Compass 0.13.alpha.0`.

FireSass reports wrong line numbers. They are roughly twice bigger than they should be.

For instance, i've got some SASS declarations on lines 21-23:

``` sass
h1, h2, h3, h4, h5, h6
  font-family : $font-serif
  color       : $color-headers-main
```

Firebug reports those to be on line 41:

```
_headers.sass (line 41)
```

But there are only 23 lines in `_headers.sass`!

Why does this happen? How do i fix it?

My `config.rb`:

``` ruby
# Require any additional compass plugins here.
require 'aurora'

# Compass configuration.
css_dir           = "stylesheets"
sass_dir          = "sass"
images_dir        = "images"
javascripts_dir   = "javascripts"
relative_assets   = true
preferred_syntax  = :sass

# Compiled CSS would be formatted for development.
# No need to make it compact because CMS will do code compression.
output_style      = :expanded #or :nested or :compact or :compressed
line_comments     = true
sass_options      = {:debug_info => true}

```

**Comment by nex3** [comment]
Are you sure this is a Firesass issue? Are the line numbers listed in the CSS file accurate?

If not, please file an issue against [nex3/sass](http://github.com/nex3/sass/issues).

**Comment by lolmaus** [comment]
Roger.
