### ISSUE TITLE
remove firebug dependency

### ISSUE THREAD

**Issue by yukulele** [nex3/firesass#20]
Firefox have now <a href="https://developer.mozilla.org/en-US/docs/Tools">it's own developer tool</a>.

FireSASS should be works with it.

**Comment by thany** [comment]
FireSass is designed specifically as a Firebug plugin. I suppose reworking it to be an Aurora plugin would imply massive changes. This calls for a separate plugin, perhaps called AuroraSass or something.

I'm not sure if it is the "job" of FireSass' author to do this. Someone else might like to build such a plugin for Aurora.
