### ISSUE TITLE
Firesass development plans for FF4 and Firebug 1.7

### ISSUE THREAD

**Issue by hungrysquirrel** [nex3/firesass#4]
Currently the Firesass plugin is not working with an Alpha version of Firebug 1.7 and I totally understand that it's unreasonable to expect you to have your extension working with Alpha software. 

I was writing to see when you were planning on development for compatibility with the new Firebug.

Many thanks for the plugin it is a major help.

Josh

**Comment by nex3** [comment]
Basically, whenever I can find time to fix it. Almost certainly after the Sass 3.1 release.

**Comment by hungrysquirrel** [comment]
Thanks for getting back to me. Will it auto-update in Firefox when you release it? Any plans for a Chrome extension?

**Comment by nex3** [comment]
I believe the Mozilla extension site takes care of auto-updating, so yes.

I would love to make a Chrome extension, but at the moment I don't think it's possible. The issue is that the Chrome dev tools are built in to the browser, and thus (I believe) can't be overridden by extensions.

**Comment by passy** [comment]
The chrome issue might change with the release of chrome 11. There is an option under "about:flags" for experimental APIs. As far as I know this provides some hooks for the development tools. I can't tell if this includes enough control to change line numbers and references, though.

**Comment by szTheory** [comment]
Is FF4 compatibility still in the works?

**Comment by nex3** [comment]
See #5.

**Comment by JohnAlbin** [comment]
Congrats on getting Sass 3.1 out the door! Hopefully getting this plug-in updated to FF4 will be relatively easy. I'm annoyed FF won't let me install the existing plugin.
