### ISSUE TITLE
FF4 Support

### ISSUE THREAD

**Issue by RogerPodacter** [nex3/firesass#5]
Any idea when this plugin will be FF4-compatible? (I CAN'T LIVE WITHOUT IT!!!)

**Comment by nex3** [comment]
Bump max Firefox version to 4.0.

Closed by 07c0448517baac39fbf84cb56ad1d4dd15b61bb6

**Comment by RogerPodacter** [comment]
YAYYYYY!!!

**Comment by RogerPodacter** [comment]
According to https://addons.mozilla.org/en-US/firefox/addon/103988, it's still not available for FF4 (the in-browser add-ons manager confirms this)

: (

**Comment by nex3** [comment]
Version 0.0.7 is awaiting review from Mozilla. You can download it from the versions page: https://addons.mozilla.org/en-US/firefox/addon/firesass-for-firebug/versions/

**Comment by RogerPodacter** [comment]
Awesome  thanks! Love this extension. Keep up the good work.

(If you like rap, you should check out Rap Genius [http://rapgenius.com],
which I built with the help of SCSS and Firesass)
