### ISSUE TITLE
Any plans to support Webkit browsers?

### ISSUE THREAD

**Issue by lmartins** [nex3/firesass#6]
Would be nice to have sass linenumber displayed in webkit css inspector.

**Comment by nex3** [comment]
Last I checked, the Webkit inspector didn't have any support for modifying the displayed line numbers via an extension. If this changes, I would certainly consider working on something like FireSass for Webkit.

**Comment by iurevych** [comment]
No changes on Webkit support?

**Comment by nex3** [comment]
I haven't learned of any change in the API, although it's possible that this has happened. Even if it were possible now, though, I doubt I'd have time to work on it.

**Comment by b1tr0t** [comment]
We've written an extension for Chrome at least, [Sass Sleuth](http://www.mobify.com/dev/sass-sleuth-debugging-sass-in-webkit-browsers/).  I'll update you if we add support for Safari!

**Comment by nex3** [comment]
Support for Chrome-compatible source maps just landed in nex3/sass@c962fa1b7d90fdb2e9df72ae2527a48f1f770276, which provides a superset of the functionality of FireSass.
