### ISSUE TITLE
Firesass fails with Firebug 1.8

### ISSUE THREAD

**Issue by lmartins** [nex3/firesass#7]
It installs without any complaint but it wont show the sass line numbers on the inspector.

Am i missing anything?

**Comment by nex3** [comment]
Are you sure you're providing the proper debug information in your Sass output?

**Comment by lmartins** [comment]
Yes, im positive. But it worked before, stopped after i've installed Firefox Aurora. Since then i've tried to reinstall everything but the result is the same. 

Firesass is not the only plugin showing problem though, even Firebug will only run from the top menu bar, wont show on the plugins menu at the bottom of the browser. Not sure if both issues have any kind of relation.

**Comment by lmartins** [comment]
I've confirmed this only happens on Firebug 1.8b1, the latest nightly, the alpha version work ok.

**Comment by fpbouchard** [comment]
The problem seems to be with Firebug 1.8. I'm having the issue using Firebug 1.8b2 in Firefox 4.0.1.

**Comment by nex3** [comment]
I'm not terribly surprised to hear that it doesn't work with Firebug 1.8; last I looked, it changed a lot of the internal infrastructure that FireSass was hooking into. I'll try to find time to write a version that works with 1.8, but it may not be terribly quick in coming.

I've updated the issue title accordingly.

**Comment by lmartins** [comment]
Next3, thanks for that. Not the best news though, but totally understandable.

**Comment by Lukom** [comment]
Sadly that it doesn't work now, please fix this!
Maybe I'll use chrome - it shows css comments at least

**Comment by alessandro-fazzi** [comment]
Hi nex3. :) No news under the sun about FireBug 1.8? I'm still in stuck with it.

**Comment by mat813** [comment]
I'd love to see it happening too :-)

**Comment by aeonbeat** [comment]
Hm, it works to me?

**Comment by ntreadway** [comment]
Not working for me. Using FireBug 1.8.4

**Comment by jjt** [comment]
Not working for me either.

Firebug 1.9.0a5
Firefox 8.0 (release channel)

**Comment by pyronaur** [comment]
Firefox 8.0 stable, FireBug 1.9.0b1, Latest version of FireSASS - doesn't work for me neither. Shame :(

**Comment by NV** [comment]
Firefox 9.0.1, Firebug 1.8.4, FireSASS from the repo (I [bumped maxVersion](https://github.com/NV/firesass/commit/5a67620bb97b988e7a7a19e9bb5e85b11d97af30) to install it into latest Firefox).

It works:

![](http://elv1s.ru/i/firesass-kinda-works.png)

By the way, when I click on line numbers links I see the following.

![](http://elv1s.ru/i/firebug-firesass-weird-filename-line.png)

Is it OK?

**Comment by pyronaur** [comment]
Ok, how do I install it from the repo ?

**Comment by NV** [comment]
```
$ git clone git://github.com/NV/firesass.git
$ cd firesass
$ rake package
Packaging FireSass 0.0.6
zip -r pkg/firesass-0.0.6.xpi . -x@.zipignore
  adding: .zipignore (deflated 4%)
  adding: chrome/ (stored 0%)
  adding: chrome/content/ (stored 0%)
  adding: chrome/content/firesass.xul (deflated 38%)
  adding: chrome/content/reps.js (deflated 67%)
  adding: chrome/locale/ (stored 0%)
  adding: chrome/locale/en-US/ (stored 0%)
  adding: chrome/locale/en-US/firesass.properties (deflated 42%)
  adding: chrome.manifest (deflated 53%)
  adding: install.rdf (deflated 53%)
  adding: license.txt (deflated 49%)
  adding: Rakefile (deflated 57%)
  adding: README.md (deflated 47%)
  adding: skin/ (stored 0%)
  adding: skin/logo.png (stored 0%)
  adding: skin/screenshot.png (deflated 2%)
  adding: VERSION (stored 0%)
```

Drag pkg/firesass-0.0.6.xpi into Firefox window to install it.

**Comment by bbodien** [comment]
That worked for me, thanks NV!

**Comment by lewang** [comment]
Is this still fixed?  :)  I'm trying the github cloned firesass with firefox 10.0.1 and firebug 1.91.

And having no luck.

**Comment by craigdx** [comment]
The latest build worked for me briefly. But currently not working with Firefox 10.0.2 and Firebug 1.9.1

Perhaps it was a minor version upgrade with FF? Not sure.

**Comment by machineghost** [comment]
Not working for me on 1.9.1.  Would be glad to offer help (I've worked with Firefox extensions before, but not Firebug extensions) if the original author needs any.

**Comment by pyronaur** [comment]
Works with Beta 12 and Firebug 1.9.1 for me.
